version: "3"
services:
  redis:
    image: redis:alpine
    ports: 
      - "6379:6379"
    volumes: 
      - ./data:/data/db
    networks: 
      - webnet
  api-server:
    container_name: api-server
    image: api-server
    ports:
      - "5000:5000"
    networks:
      - webnet
networks:
  webnet: